
import type { Service, PortfolioItem, TeamMember, Testimonial, BlogPost } from './types';
import CodeIcon from './components/icons/CodeIcon';
import MobileIcon from './components/icons/MobileIcon';
import DesignIcon from './components/icons/DesignIcon';
import CartIcon from './components/icons/CartIcon';
import MegaphoneIcon from './components/icons/MegaphoneIcon';
import PencilIcon from './components/icons/PencilIcon';
import LightbulbIcon from './components/icons/LightbulbIcon';
import ConsultingIcon from './components/icons/ConsultingIcon';

export const services: Service[] = [
  {
    icon: CodeIcon,
    title: 'Web Development',
    description: 'We craft responsive, secure, and high-performance websites tailored to your needs, from simple landing pages to complex web applications.',
    technologies: ['HTML5', 'CSS3', 'JavaScript', 'React', 'Node.js', 'MongoDB', 'PostgreSQL'],
  },
  {
    icon: MobileIcon,
    title: 'Mobile App Development',
    description: 'We build user-friendly mobile apps for iOS and Android, ensuring a seamless experience across devices.',
    technologies: ['Swift', 'Kotlin', 'React Native', 'Flutter'],
  },
  {
    icon: DesignIcon,
    title: 'UI/UX Design',
    description: 'Our designs prioritize user experience and aesthetics, creating interfaces that engage and convert.',
    technologies: ['Figma', 'Adobe XD', 'Sketch', 'InVision'],
  },
  {
    icon: CartIcon,
    title: 'E-commerce Solutions',
    description: 'We develop robust online stores with secure payment gateways and inventory management to drive your business growth.',
    technologies: ['Shopify', 'WooCommerce', 'Magento', 'Custom Solutions'],
  },
  {
    icon: MegaphoneIcon,
    title: 'Digital Marketing',
    description: 'We boost your online presence with SEO, social media campaigns, and email marketing strategies.',
    technologies: ['SEO', 'PPC Advertising', 'Content Marketing', 'SMM'],
  },
  {
    icon: PencilIcon,
    title: 'Content Creation',
    description: 'We produce compelling content, including blog posts, videos, and graphics, to tell your brand’s story.',
    technologies: ['Copywriting', 'Videography', 'Graphic Design'],
  },
  {
    icon: LightbulbIcon,
    title: 'Branding',
    description: 'We shape your brand identity with logos, color schemes, and messaging that resonate with your audience.',
    technologies: ['Logo Design', 'Brand Strategy', 'Style Guides'],
  },
  {
    icon: ConsultingIcon,
    title: 'Digital Strategy Consulting',
    description: 'We provide expert guidance on digital strategies and technology adoption to help you succeed.',
    technologies: ['Roadmapping', 'Tech Audits', 'Market Analysis'],
  },
];

export const portfolioItems: PortfolioItem[] = [
  {
    id: 1,
    image: 'https://images.unsplash.com/photo-1523381294911-8d3cead13475?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&fit=max',
    title: 'E-commerce Platform for Luxe Apparel',
    category: 'E-commerce',
    client: 'Luxe Apparel Co.',
    year: 2023,
    servicesProvided: ['E-commerce Development', 'UI/UX Design', 'Headless CMS'],
    technologies: ['Shopify Plus', 'React', 'GraphQL', 'Contentful', 'Node.js'],
    keyFeatures: [
      'Seamless mobile shopping experience',
      'Custom 3D product visualization',
      'Personalized user accounts and wishlists',
      'Integrated marketing automation'
    ],
    description: 'A bespoke, high-performance e-commerce solution designed for a luxury fashion brand to elevate their online presence and drive sales.',
    challenge: 'The client needed a scalable online store that could handle high traffic, showcase their luxury products with elegance, and integrate with their existing inventory system without compromising on speed or design.',
    solution: 'We built a custom platform using a headless architecture with Shopify Plus on the backend and a lightning-fast React frontend. This allowed for complete design freedom and integration with a CMS for dynamic content, creating a seamless and luxurious user experience.',
    result: 'Boosted client sales by 45% and increased user engagement by 60% within the first six months. The new platform also reduced page load times by 50%.',
  },
  {
    id: 2,
    image: 'https://images.unsplash.com/photo-1554224155-1696413565d3?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&fit=max',
    title: 'Fintech Mobile App "CoinFlow"',
    category: 'Mobile App',
    client: 'CoinFlow Inc.',
    year: 2022,
    servicesProvided: ['Mobile App Development', 'UI/UX Design', 'API Integration'],
    technologies: ['Swift', 'Kotlin', 'Plaid API', 'Firebase', 'AWS'],
     keyFeatures: [
      'Secure bank account linking via Plaid',
      'Real-time transaction categorization',
      'Intelligent budgeting and goal setting',
      'Data-driven financial insights'
    ],
    description: 'An intuitive and secure mobile app for personal finance management, designed to empower users to take control of their financial health.',
    challenge: 'To create a highly secure and user-friendly app that simplifies budgeting and expense tracking for millennials, while handling sensitive financial data with the utmost care.',
    solution: 'Developed native apps for iOS and Android using Swift and Kotlin, featuring multi-layered security protocols, real-time transaction syncing via the Plaid API, and engaging data visualization to make finance management accessible and easy.',
    result: 'Achieved 100,000+ downloads in the first year and a 4.8-star rating on both app stores. Featured by Apple as "App of the Day".',
  },
  {
    id: 3,
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&fit=max',
    title: 'Corporate Rebranding for TechCorp',
    category: 'Branding',
    client: 'TechCorp Solutions',
    year: 2023,
    servicesProvided: ['Branding', 'Web Design', 'Content Strategy'],
    technologies: ['Figma', 'Adobe Illustrator', 'Webflow', 'Google Analytics'],
    keyFeatures: [
      'Modern and versatile logo system',
      'Comprehensive brand style guide',
      'Redesigned marketing website',
      'Data-driven content strategy'
    ],
    description: 'A complete brand overhaul for a B2B technology company to modernize its image and better communicate its value proposition.',
    challenge: 'TechCorp\'s branding was outdated and didn\'t reflect its innovative services. They needed a modern, cohesive identity to stand out in a competitive market and attract enterprise-level clients.',
    solution: 'We conducted a full brand strategy workshop, designed a new logo, color palette, and typography system, and created a comprehensive brand style guide. This was followed by a complete redesign of their corporate website and marketing materials.',
    result: 'Increased brand recognition by 30% and improved lead quality, contributing to a 20% rise in enterprise contracts. The new website saw a 40% decrease in bounce rate.',
  },
  {
    id: 4,
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&fit=max',
    title: 'SaaS Platform "InnovateHub"',
    category: 'Web Development',
    client: 'InnovateHub Inc.',
    year: 2024,
    servicesProvided: ['Web Development', 'UI/UX Design', 'SaaS Architecture'],
    technologies: ['React', 'Node.js', 'PostgreSQL', 'WebSockets', 'AWS'],
    keyFeatures: [
      'Real-time document collaboration',
      'Advanced project management tools',
      'Role-based access control (RBAC)',
      'Third-party app integrations'
    ],
    description: 'A collaborative web application designed to streamline project management and innovation for remote teams.',
    challenge: 'The client wanted a feature-rich SaaS platform with real-time collaboration tools, robust security, an intuitive UI, and the ability to scale to thousands of concurrent users.',
    solution: 'We built a scalable web app using React, Node.js, and WebSockets for real-time features. The infrastructure was designed on AWS for reliability and scalability. The UI/UX was meticulously designed in Figma to ensure ease of use for complex workflows.',
    result: 'Successfully onboarded over 500 teams in the beta phase and secured a significant round of seed funding based on the platform\'s performance and user feedback.',
  },
  {
    id: 5,
    image: 'https://images.unsplash.com/photo-1576158113480-534d5b248a33?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&fit=max',
    title: 'Health & Wellness App "Vitality"',
    category: 'Mobile App',
    client: 'Vitality Health',
    year: 2023,
    servicesProvided: ['Mobile App Development', 'UI/UX Design', 'Wearable Integration'],
    technologies: ['React Native', 'Firebase', 'Apple HealthKit', 'Google Fit'],
    keyFeatures: ['Activity tracking', 'Personalized coaching', 'Mindfulness exercises', 'Community challenges'],
    description: 'A holistic health and wellness app that helps users track their activity, practice mindfulness, and connect with a supportive community.',
    challenge: 'Creating an engaging app that unifies physical and mental wellness metrics in a simple, motivating interface, while integrating smoothly with native health APIs.',
    solution: 'We developed a cross-platform app with React Native, integrating HealthKit and Google Fit for seamless data syncing. The UI was designed to be calming and motivational, with gamified elements to encourage consistent use.',
    result: 'Featured on health and fitness blogs, leading to 50,000 active users in 6 months. Users reported a 25% increase in daily physical activity.',
  },
  {
    id: 6,
    image: 'https://images.unsplash.com/photo-1503676260728-1c64c1bae54f?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&fit=max',
    title: 'Online Learning Platform "Academa"',
    category: 'Web Development',
    client: 'Academa Education',
    year: 2022,
    servicesProvided: ['Web Development', 'Video Streaming', 'Payment Integration'],
    technologies: ['Vue.js', 'Node.js', 'Stripe', 'Mux Video API'],
    keyFeatures: ['On-demand video courses', 'Interactive quizzes', 'Instructor dashboards', 'Student forums'],
    description: 'A modern e-learning platform that empowers creators to build and sell online courses.',
    challenge: 'To build a platform that supports high-quality video streaming, secure payment processing, and interactive learning tools, while being easy for instructors to manage.',
    solution: 'We created a robust platform with a Vue.js frontend for a reactive user experience. Mux was integrated for reliable video streaming and DRM, while Stripe Connect handled complex payment splitting for instructors.',
    result: 'Over 1,000 courses were created within the first year, with a 95% satisfaction rate from instructors and students alike.',
  },
  {
    id: 7,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&fit=max',
    title: 'Real Estate Portal "NestHub"',
    category: 'Web Development',
    client: 'NestHub Properties',
    year: 2023,
    servicesProvided: ['Web Development', 'Map Integration', 'Data Visualization'],
    technologies: ['Next.js', 'Mapbox', 'PostgreSQL', 'Prisma'],
    keyFeatures: ['Advanced property search filters', 'Interactive map view', 'Virtual tours', 'Agent profiles'],
    description: 'A comprehensive real estate portal connecting buyers, sellers, and agents with powerful search and visualization tools.',
    challenge: 'The client needed a fast, SEO-friendly platform capable of handling thousands of listings with complex search queries and a highly interactive map interface.',
    solution: 'We used Next.js for server-side rendering to ensure fast load times and optimal SEO. Mapbox was integrated for a high-performance map experience, and a powerful backend was built to handle complex filtering logic.',
    result: 'Became the top-ranked real estate portal in its local market within a year, with a 70% increase in lead generation for agents.',
  },
  {
    id: 8,
    image: 'https://images.unsplash.com/photo-1488521787991-ed7b2f28a727?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&fit=max',
    title: 'Non-Profit Website for "GreenFuture"',
    category: 'Web Design',
    client: 'GreenFuture Org',
    year: 2024,
    servicesProvided: ['Web Design', 'CMS Development', 'Donation Integration'],
    technologies: ['Webflow', 'Stripe', 'Lottie'],
    keyFeatures: ['Impact storytelling', 'Easy donation process', 'Volunteer sign-up forms', 'Project showcases'],
    description: 'An engaging and inspiring website to help a non-profit organization increase donations and attract volunteers.',
    challenge: 'To create a visually compelling site that clearly communicates the organization\'s mission and impact, making it easy and secure for users to donate.',
    solution: 'We designed a storytelling-focused website in Webflow, using powerful imagery and Lottie animations to engage visitors. A seamless donation flow was integrated directly using Stripe.',
    result: 'Online donations increased by 200% in the first quarter after launch, and volunteer sign-ups tripled.',
  },
  {
    id: 9,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&fit=max',
    title: 'Restaurant Reservation System "Tabled"',
    category: 'Web Application',
    client: 'The Gourmet Group',
    year: 2023,
    servicesProvided: ['Web App Development', 'UI/UX Design', 'API Development'],
    technologies: ['React', 'Python (Django)', 'PostgreSQL', 'Twilio'],
    keyFeatures: ['Real-time table management', 'Online booking widget', 'Automated SMS reminders', 'Guest database'],
    description: 'A complete reservation and table management system for restaurants to streamline operations and enhance the guest experience.',
    challenge: 'To replace phone-based reservation systems with an efficient digital solution that manages bookings, waitlists, and guest preferences in real-time.',
    solution: 'We built a React-based dashboard for restaurant staff and a simple booking widget for their websites. The Django backend handles reservation logic, and Twilio integration automates guest communication.',
    result: 'Reduced no-shows by 30% thanks to automated reminders and helped partner restaurants increase table turnover by 15%.',
  },
  {
    id: 10,
    image: 'https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&fit=max',
    title: 'Custom CRM for a Sales Team',
    category: 'SaaS Platform',
    client: 'Momentum Sales',
    year: 2022,
    servicesProvided: ['SaaS Development', 'Data Migration', 'Third-party Integrations'],
    technologies: ['Angular', '.NET Core', 'SQL Server', 'Azure'],
    keyFeatures: ['Custom sales pipelines', 'Automated lead scoring', 'Email integration', 'Performance analytics'],
    description: 'A bespoke CRM platform built from the ground up to match the unique sales workflow of a fast-growing enterprise team.',
    challenge: 'Off-the-shelf CRMs were too rigid for the client\'s unique sales process. They needed a flexible, custom solution that could integrate with their existing tools.',
    solution: 'We developed a fully custom CRM with a modular architecture on Azure. The system was designed around their specific pipeline stages and integrated seamlessly with their email and calendar systems.',
    result: 'Increased sales team productivity by 40% and provided management with clear, actionable insights into performance.',
  },
  {
    id: 11,
    image: 'https://images.unsplash.com/photo-1522199710521-72d69614c702?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&fit=max',
    title: 'Travel Booking Site "Wanderlust"',
    category: 'E-commerce',
    client: 'Wanderlust Travel',
    year: 2023,
    servicesProvided: ['Web Development', 'API Integration', 'UI/UX Design'],
    technologies: ['React', 'Node.js', 'Amadeus API', 'Stripe'],
    keyFeatures: ['Flight & hotel search', 'Multi-city trip planner', 'User reviews', 'Secure checkout'],
    description: 'A user-friendly travel booking website that aggregates flights and hotels to help users find the best deals.',
    challenge: 'To integrate multiple third-party travel APIs and present complex data in a simple, intuitive, and fast interface that encourages booking.',
    solution: 'We built a fast single-page application using React, integrating the Amadeus API for travel data. The backend handles caching and aggregation to ensure quick search results.',
    result: 'Achieved a 20% higher conversion rate than the industry average due to the intuitive design and fast performance.',
  },
  {
    id: 12,
    image: 'https://images.unsplash.com/photo-1611926653458-09294b3142d5?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&fit=max',
    title: 'Social Media Analytics "SocialPulse"',
    category: 'SaaS Platform',
    client: 'SocialPulse Analytics',
    year: 2024,
    servicesProvided: ['SaaS Development', 'Data Visualization', 'API Integration'],
    technologies: ['React', 'Python (Flask)', 'MongoDB', 'D3.js'],
    keyFeatures: ['Competitor tracking', 'Sentiment analysis', 'Campaign reporting', 'Influencer discovery'],
    description: 'A powerful SaaS tool for marketers to track and analyze social media performance with beautiful data visualizations.',
    challenge: 'To process vast amounts of data from social media APIs in real-time and present it in insightful, easy-to-understand dashboards.',
    solution: 'We architected a scalable data processing pipeline in Python and used MongoDB to store unstructured social data. The frontend features highly interactive charts and graphs built with React and D3.js.',
    result: 'Acquired by a major marketing tech company 18 months after launch.',
  },
  {
    id: 13,
    image: 'https://images.unsplash.com/photo-1586528116311-01dd6c5181b2?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&fit=max',
    title: 'Logistics Dashboard "ShipRight"',
    category: 'Web Application',
    client: 'ShipRight Logistics',
    year: 2023,
    servicesProvided: ['Web App Development', 'Real-time Tracking', 'UI/UX Design'],
    technologies: ['Vue.js', 'Go', 'PostgreSQL', 'Google Maps API'],
    keyFeatures: ['Real-time shipment tracking', 'Route optimization', 'Automated alerts', 'Performance analytics'],
    description: 'A real-time logistics dashboard for a freight company to monitor and manage their entire fleet of shipments.',
    challenge: 'The client needed a high-performance system to track hundreds of shipments simultaneously and provide actionable alerts for potential delays.',
    solution: 'We built a highly responsive frontend with Vue.js and a backend in Go for high concurrency. Google Maps API was used for real-time location visualization and route optimization.',
    result: 'Improved on-time delivery rate by 25% and reduced fuel costs by 10% through better route planning.',
  },
  {
    id: 14,
    image: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&fit=max',
    title: 'Event Management Platform "EventFull"',
    category: 'Web Application',
    client: 'EventFull Conferences',
    year: 2022,
    servicesProvided: ['Web Development', 'Ticketing System', 'Mobile App'],
    technologies: ['React', 'Node.js', 'Stripe', 'Flutter'],
    keyFeatures: ['Event landing pages', 'Tiered ticketing', 'QR code check-in', 'Attendee networking'],
    description: 'An all-in-one platform for conference organizers to create, promote, and manage events.',
    challenge: 'To build a comprehensive solution that handles event marketing, ticket sales, and on-site check-in, including a mobile app for attendees.',
    solution: 'We created a web platform for organizers and a companion mobile app for attendees using Flutter. The system features a custom ticketing engine with Stripe for payments and QR code generation for check-in.',
    result: 'Used to manage over 200 events in its first two years, processing over $5 million in ticket sales.',
  },
  {
    id: 15,
    image: 'https://images.unsplash.com/photo-1490725263030-1f052138a83b?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&fit=max',
    title: 'Fashion Blog & Lookbook "The Style Edit"',
    category: 'Content/Branding',
    client: 'Chloe Renaud',
    year: 2023,
    servicesProvided: ['Web Design', 'Branding', 'Headless CMS'],
    technologies: ['Gatsby', 'Contentful', 'GraphQL'],
    keyFeatures: ['Magazine-style layout', 'Shoppable articles', 'High-res image galleries', 'Lightning-fast performance'],
    description: 'A visually stunning and high-performance blog and lookbook for a major fashion influencer.',
    challenge: 'To create an image-heavy website that was extremely fast, SEO-friendly, and easy for the client to update with new content daily.',
    solution: 'We used a static site generator, Gatsby, combined with a headless CMS (Contentful). This approach provides incredible performance and security, while giving the client a simple interface for content management.',
    result: 'Organic search traffic increased by 150%, and affiliate link click-throughs rose by 60% due to the enhanced user experience.',
  },
  {
    id: 16,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&fit=max',
    title: 'Food Delivery App "QuickBites"',
    category: 'Mobile App',
    client: 'QuickBites Delivery',
    year: 2024,
    servicesProvided: ['Mobile App Development', 'Real-time Tracking', 'Payment Integration'],
    technologies: ['Flutter', 'Firebase', 'Google Maps API', 'Stripe'],
    keyFeatures: ['Restaurant discovery', 'Live order tracking', 'In-app payments', 'Driver & customer apps'],
    description: 'A complete food delivery ecosystem, including apps for customers, restaurants, and delivery drivers.',
    challenge: 'To build a three-sided marketplace with real-time logistics, location tracking, and payment processing, ensuring a smooth experience for all users.',
    solution: 'We used Flutter to develop for iOS and Android simultaneously from a single codebase. Firebase handled the real-time database and authentication needs, while Google Maps API provided the core logistics and tracking features.',
    result: 'Launched successfully in a major city, onboarding 300+ restaurants and completing 10,000+ orders in the first three months.',
  },
  {
    id: 17,
    image: 'https://images.unsplash.com/photo-1615874987514-c352d3acc33c?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&fit=max',
    title: 'Smart Home App "HomeSphere"',
    category: 'Mobile App',
    client: 'HomeSphere Inc.',
    year: 2023,
    servicesProvided: ['Mobile App Development', 'IoT Integration', 'UI/UX Design'],
    technologies: ['Swift (iOS)', 'Kotlin (Android)', 'MQTT', 'AWS IoT'],
    keyFeatures: ['Unified device control', 'Custom automations & scenes', 'Energy usage monitoring', 'Secure remote access'],
    description: 'An elegant mobile app to control a wide range of smart home devices from different brands in one place.',
    challenge: 'To create a single, intuitive interface that can communicate with various IoT devices using different protocols, while ensuring reliability and security.',
    solution: 'We developed native mobile apps for the best performance and device access. An AWS IoT backend with an MQTT broker was used to standardize communication between the app and various smart devices.',
    result: 'Partnered with three major smart home device manufacturers to become their official companion app.',
  },
  {
    id: 18,
    image: 'https://images.unsplash.com/photo-1589998059171-988d887df646?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&fit=max',
    title: 'Legal Tech Document Manager "DocuSafe"',
    category: 'SaaS Platform',
    client: 'JurisTech',
    year: 2024,
    servicesProvided: ['SaaS Development', 'Cloud Security', 'Full-text Search'],
    technologies: ['React', 'Node.js', 'Elasticsearch', 'AWS S3'],
    keyFeatures: ['Secure document storage', 'Version control', 'Advanced full-text search', 'Granular access permissions'],
    description: 'A secure, cloud-based document management system designed specifically for law firms.',
    challenge: 'To build a platform with enterprise-grade security, compliance (e.g., GDPR), and a powerful search engine capable of indexing millions of legal documents.',
    solution: 'We built the platform on AWS, using S3 for encrypted storage and Elasticsearch for powerful and fast full-text search capabilities. The system included detailed audit logs and role-based access control.',
    result: 'Adopted by 20 law firms within the first year, managing over 5 million sensitive documents securely.',
  },
  {
    id: 19,
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&fit=max',
    title: 'Artist Portfolio for Ana Ivanov',
    category: 'Web Design',
    client: 'Ana Ivanov',
    year: 2023,
    servicesProvided: ['Web Design', 'CMS Integration', 'E-commerce'],
    technologies: ['Next.js', 'Sanity.io', 'Shopify Lite'],
    keyFeatures: ['Minimalist design', 'High-resolution galleries', 'Integrated print shop', 'Exhibition listings'],
    description: 'A clean, minimalist portfolio website for a contemporary artist to showcase her work and sell prints.',
    challenge: 'To design a site where the artwork is the absolute focus, with an unobtrusive UI, fast-loading high-resolution images, and a simple way to sell prints.',
    solution: 'We used Next.js for a fast, static front-end and Sanity.io as a headless CMS, which gave the artist an easy way to upload new work. Shopify Lite was integrated for a lightweight e-commerce solution for prints.',
    result: 'Praised in multiple art blogs for its design. The artist saw a 300% increase in online print sales.',
  },
  {
    id: 20,
    image: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1200&fit=max',
    title: 'Music Streaming Service "TuneWave"',
    category: 'Web Application',
    client: 'TuneWave Audio',
    year: 2024,
    servicesProvided: ['Web App Development', 'Audio Streaming', 'Recommendation Engine'],
    technologies: ['React', 'Python (FastAPI)', 'PostgreSQL', 'Redis'],
    keyFeatures: ['Vast music library', 'AI-powered playlists', 'Social features', 'Lossless audio option'],
    description: 'A web-based music streaming service aimed at audiophiles, with a focus on high-quality audio and smart recommendations.',
    challenge: 'To build a platform capable of streaming high-fidelity audio reliably to thousands of concurrent users and develop a recommendation engine that surfaces new music effectively.',
    solution: 'We built a custom audio streaming pipeline using FastAPI for speed. A machine learning model was developed to generate personalized recommendations, and Redis was used to cache user data for a snappy experience.',
    result: 'Gained a dedicated user base of 10,000 audiophiles in its beta phase through word-of-mouth.',
  }
];


export const teamMembers: TeamMember[] = [
  {
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max',
    name: 'Jane Doe',
    role: 'Founder & CEO',
    bio: 'With over 15 years in the industry, Jane is the visionary behind BigTink, driving innovation and client success.',
  },
  {
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max',
    name: 'John Smith',
    role: 'Chief Technology Officer',
    bio: 'John is a full-stack guru who leads our talented development team, turning complex challenges into elegant solutions.',
  },
  {
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max',
    name: 'Emily White',
    role: 'Head of Design',
    bio: 'Emily\'s passion for user-centric design ensures that every project we deliver is both beautiful and intuitive.',
  },
  {
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max',
    name: 'Michael Brown',
    role: 'Director of Digital Marketing',
    bio: 'Michael crafts data-driven marketing strategies that elevate brands and deliver measurable results.',
  },
];

export const testimonials: Testimonial[] = [
  {
    quote: 'BigTink Digital Creations transformed our online presence. Their team is professional, creative, and delivered beyond our expectations.',
    author: 'Alex Johnson',
    company: 'CEO, Luxe Apparel',
  },
  {
    quote: 'The mobile app they developed is flawless. Their attention to detail and commitment to quality is unmatched.',
    author: 'Samantha Lee',
    company: 'Founder, CoinFlow',
  },
  {
    quote: 'Working with BigTink was a game-changer for our brand. Their strategic insights and design expertise are top-notch.',
    author: 'David Chen',
    company: 'CMO, TechCorp',
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: 1,
    image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=600&fit=max',
    title: 'The Future of Web Development: Trends to Watch in 2024',
    excerpt: 'From AI integration to sustainable web design, we explore the key trends shaping the future of the web...',
    author: 'John Smith',
    date: 'October 26, 2023',
  },
  {
    id: 2,
    image: 'https://images.unsplash.com/photo-1559028006-448665bd7c20?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=600&fit=max',
    title: 'Why User Experience (UX) is the Key to Customer Loyalty',
    excerpt: 'A great product isn\'t enough. Discover why a seamless user experience is crucial for retaining customers and growing your business...',
    author: 'Emily White',
    date: 'October 15, 2023',
  },
  {
    id: 3,
    image: 'https://images.unsplash.com/photo-1557862921-37829c790f19?ixlib=rb-4.0.3&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=600&fit=max',
    title: 'Unlocking Growth: A Guide to Full-Funnel Digital Marketing',
    excerpt: 'Learn how to create a holistic digital marketing strategy that engages customers at every stage of their journey...',
    author: 'Michael Brown',
    date: 'September 28, 2023',
  },
];
